const ja = {
 language:'言語',eyebrow:'デザインで、気分を変える。',title:'あなたなら、どんな顔？',intro:'色を選んだり、顔を変えたり。新しいHead-Lightを、少しお試し。',preview:'ホーム画面のプレビュー',choose:'好きな組み合わせに。',reset:'最初に戻す',style:'スタイル',simple:'シンプル',illustration:'イラスト',background:'背景',accent:'アクセント',face:'顔あそび',size:'大きさ',spacing:'間隔',height:'高さ',motion:'まばたき',retro:'レトロモード',note:'デザインの一部を試せる体験版です。入力・録音などはできません。',release:'新しいデザインは、次のアップデートでお届けします。',back:'← Head-Lightについて',white:'白',black:'黒',charcoal:'チャコール',navy:'夜ふけ',cream:'クリーム',paper:'紙',mono:'モノクロ',sumi:'墨',blue:'ブルー',lime:'ライム',orange:'オレンジ',pink:'ピンク',lilac:'藤',mint:'ミント',lcdGreen:'液晶グリーン',amber:'アンバー',sky:'スカイ',rose:'ローズ',smoke:'スモーク',lavender:'ラベンダー',smile:'にっこり',kira:'きらきら',tare:'たれ目',sleepy:'ねむい',round:'まんまる',tojime:'ぎゅっと',ring:'びっくり',home:'ホーム',words:'言葉',collection:'コレクション',journal:'手帳',ai:'AIに渡す'
};
const en = {
 language:'Language',eyebrow:'A little change of mood.',title:'What’s your kind of face?',intro:'Pick a color. Try a different face. Make yourself at home in the new Head-Light.',preview:'Home screen preview',choose:'Make it your own.',reset:'Reset',style:'Style',simple:'Simple',illustration:'Illustration',background:'Background',accent:'Accent',face:'Face play',size:'Size',spacing:'Spacing',height:'Height',motion:'Blinking',retro:'Retro mode',note:'A small taste of the design options. Typing and recording are not available in this preview.',release:'The new design is coming in the next app update.',back:'← About Head-Light',white:'White',black:'Black',charcoal:'Charcoal',navy:'Midnight',cream:'Cream',paper:'Paper',mono:'Monochrome',sumi:'Ink',blue:'Blue',lime:'Lime',orange:'Orange',pink:'Pink',lilac:'Lilac',mint:'Mint',lcdGreen:'LCD green',amber:'Amber',sky:'Sky',rose:'Rose',smoke:'Smoke',lavender:'Lavender',smile:'Smile',kira:'Sparkle',tare:'Soft eyes',sleepy:'Sleepy',round:'Round',tojime:'Squeeze',ring:'Surprise',home:'Home',words:'Words',collection:'Collection',journal:'Journal',ai:'For AI'
};

const ko = {
  "language": "언어",
  "eyebrow": "디자인으로 기분 전환.",
  "title": "어떤 얼굴이 마음에 드세요?",
  "intro": "색을 고르고 얼굴을 바꿔 보세요. 새로운 Head-Light를 가볍게 체험해 보세요.",
  "preview": "홈 화면 미리보기",
  "choose": "취향대로 조합해 보세요.",
  "reset": "처음으로",
  "style": "스타일",
  "simple": "심플",
  "illustration": "일러스트",
  "background": "배경",
  "accent": "강조색",
  "face": "얼굴 놀이",
  "size": "크기",
  "spacing": "간격",
  "height": "높이",
  "motion": "눈 깜빡임",
  "retro": "레트로 모드",
  "note": "디자인의 일부를 체험할 수 있어요. 이 미리보기에서는 입력과 녹음을 할 수 없어요.",
  "release": "새 디자인은 다음 앱 업데이트에서 만나실 수 있어요.",
  "back": "← Head-Light 소개",
  "white": "흰색",
  "black": "검정",
  "charcoal": "차콜",
  "navy": "깊은 밤",
  "cream": "크림",
  "paper": "종이",
  "mono": "모노크롬",
  "sumi": "먹색",
  "blue": "파랑",
  "lime": "라임",
  "orange": "주황",
  "pink": "분홍",
  "lilac": "연보라",
  "mint": "민트",
  "lcdGreen": "LCD 그린",
  "amber": "앰버",
  "sky": "하늘",
  "rose": "로즈",
  "smoke": "스모크",
  "lavender": "라벤더",
  "smile": "미소",
  "kira": "반짝반짝",
  "tare": "처진 눈",
  "sleepy": "졸려요",
  "round": "동그란 눈",
  "tojime": "꼭 감은 눈",
  "ring": "깜짝",
  "home": "홈",
  "words": "말",
  "collection": "컬렉션",
  "journal": "다이어리",
  "ai": "AI에게"
};
const de = {
  "language": "Sprache",
  "eyebrow": "Ein neuer Look, eine andere Stimmung.",
  "title": "Welches Gesicht passt zu dir?",
  "intro": "Wähle Farben und probiere Gesichter aus. Entdecke das neue Design von Head-Light.",
  "preview": "Vorschau des Startbildschirms",
  "choose": "Ganz nach deinem Geschmack.",
  "reset": "Zurücksetzen",
  "style": "Stil",
  "simple": "Schlicht",
  "illustration": "Illustration",
  "background": "Hintergrund",
  "accent": "Akzent",
  "face": "Gesichter",
  "size": "Größe",
  "spacing": "Abstand",
  "height": "Höhe",
  "motion": "Blinzeln",
  "retro": "Retro-Modus",
  "note": "Hier kannst du einige Designoptionen ausprobieren. Texteingabe und Aufnahme sind in dieser Vorschau nicht verfügbar.",
  "release": "Das neue Design kommt mit dem nächsten App-Update.",
  "back": "← Über Head-Light",
  "white": "Weiß",
  "black": "Schwarz",
  "charcoal": "Anthrazit",
  "navy": "Mitternacht",
  "cream": "Creme",
  "paper": "Papier",
  "mono": "Monochrom",
  "sumi": "Tusche",
  "blue": "Blau",
  "lime": "Limette",
  "orange": "Orange",
  "pink": "Pink",
  "lilac": "Flieder",
  "mint": "Minze",
  "lcdGreen": "LCD-Grün",
  "amber": "Bernstein",
  "sky": "Himmel",
  "rose": "Rosé",
  "smoke": "Rauch",
  "lavender": "Lavendel",
  "smile": "Lächeln",
  "kira": "Funkeln",
  "tare": "Sanft",
  "sleepy": "Müde",
  "round": "Rund",
  "tojime": "Zugekniffen",
  "ring": "Überrascht",
  "home": "Home",
  "words": "Worte",
  "collection": "Sammlung",
  "journal": "Tagebuch",
  "ai": "Für KI"
};
const zhHant = {
  "language": "語言",
  "eyebrow": "換個設計，換個心情。",
  "title": "你喜歡哪一張臉？",
  "intro": "選個顏色，換個表情。輕鬆體驗全新的 Head-Light。",
  "preview": "主畫面預覽",
  "choose": "自由搭配你的喜好。",
  "reset": "恢復預設",
  "style": "風格",
  "simple": "簡約",
  "illustration": "插畫",
  "background": "背景",
  "accent": "強調色",
  "face": "臉部遊戲",
  "size": "大小",
  "spacing": "間距",
  "height": "高度",
  "motion": "眨眼",
  "retro": "復古模式",
  "note": "這裡可以體驗部分設計選項。預覽不支援輸入或錄音。",
  "release": "全新設計將於下一次 App 更新推出。",
  "back": "← 關於 Head-Light",
  "white": "白",
  "black": "黑",
  "charcoal": "炭灰",
  "navy": "深夜",
  "cream": "奶油",
  "paper": "紙",
  "mono": "單色",
  "sumi": "墨",
  "blue": "藍",
  "lime": "萊姆綠",
  "orange": "橙",
  "pink": "粉紅",
  "lilac": "藤紫",
  "mint": "薄荷",
  "lcdGreen": "液晶綠",
  "amber": "琥珀",
  "sky": "天空",
  "rose": "玫瑰",
  "smoke": "煙灰",
  "lavender": "薰衣草",
  "smile": "微笑",
  "kira": "閃亮",
  "tare": "垂眼",
  "sleepy": "睏了",
  "round": "圓圓",
  "tojime": "緊閉",
  "ring": "驚訝",
  "home": "主頁",
  "words": "文字",
  "collection": "收藏",
  "journal": "手帳",
  "ai": "交給 AI"
};
const fr = {
  "language": "Langue",
  "eyebrow": "Un design, une autre humeur.",
  "title": "Quel visage vous ressemble ?",
  "intro": "Choisissez une couleur, essayez un visage. Découvrez le nouveau design de Head-Light.",
  "preview": "Aperçu de l’écran d’accueil",
  "choose": "À votre façon.",
  "reset": "Réinitialiser",
  "style": "Style",
  "simple": "Simple",
  "illustration": "Illustration",
  "background": "Arrière-plan",
  "accent": "Accent",
  "face": "Visages",
  "size": "Taille",
  "spacing": "Écart",
  "height": "Hauteur",
  "motion": "Clignement",
  "retro": "Mode rétro",
  "note": "Essayez une partie des options de design. La saisie et l’enregistrement ne sont pas disponibles dans cet aperçu.",
  "release": "Le nouveau design arrive avec la prochaine mise à jour de l’app.",
  "back": "← À propos de Head-Light",
  "white": "Blanc",
  "black": "Noir",
  "charcoal": "Anthracite",
  "navy": "Minuit",
  "cream": "Crème",
  "paper": "Papier",
  "mono": "Monochrome",
  "sumi": "Encre",
  "blue": "Bleu",
  "lime": "Citron vert",
  "orange": "Orange",
  "pink": "Rose vif",
  "lilac": "Lilas",
  "mint": "Menthe",
  "lcdGreen": "Vert LCD",
  "amber": "Ambre",
  "sky": "Ciel",
  "rose": "Rose",
  "smoke": "Fumée",
  "lavender": "Lavande",
  "smile": "Sourire",
  "kira": "Éclat",
  "tare": "Doux",
  "sleepy": "Sommeil",
  "round": "Rond",
  "tojime": "Serré",
  "ring": "Surprise",
  "home": "Accueil",
  "words": "Mots",
  "collection": "Collection",
  "journal": "Journal",
  "ai": "Pour l’IA"
};
const es = {
  "language": "Idioma",
  "eyebrow": "Un diseño para cada ánimo.",
  "title": "¿Qué cara va contigo?",
  "intro": "Elige un color, prueba otra cara. Descubre el nuevo diseño de Head-Light.",
  "preview": "Vista previa de la pantalla de inicio",
  "choose": "Combínalo a tu gusto.",
  "reset": "Restablecer",
  "style": "Estilo",
  "simple": "Simple",
  "illustration": "Ilustración",
  "background": "Fondo",
  "accent": "Acento",
  "face": "Caras",
  "size": "Tamaño",
  "spacing": "Separación",
  "height": "Altura",
  "motion": "Parpadeo",
  "retro": "Modo retro",
  "note": "Prueba algunas opciones de diseño. Esta vista previa no permite escribir ni grabar.",
  "release": "El nuevo diseño llegará con la próxima actualización de la app.",
  "back": "← Acerca de Head-Light",
  "white": "Blanco",
  "black": "Negro",
  "charcoal": "Carbón",
  "navy": "Medianoche",
  "cream": "Crema",
  "paper": "Papel",
  "mono": "Monocromo",
  "sumi": "Tinta",
  "blue": "Azul",
  "lime": "Lima",
  "orange": "Naranja",
  "pink": "Rosa vivo",
  "lilac": "Lila",
  "mint": "Menta",
  "lcdGreen": "Verde LCD",
  "amber": "Ámbar",
  "sky": "Cielo",
  "rose": "Rosa",
  "smoke": "Humo",
  "lavender": "Lavanda",
  "smile": "Sonrisa",
  "kira": "Brillo",
  "tare": "Suave",
  "sleepy": "Sueño",
  "round": "Redonda",
  "tojime": "Apretada",
  "ring": "Sorpresa",
  "home": "Inicio",
  "words": "Palabras",
  "collection": "Colección",
  "journal": "Diario",
  "ai": "Para IA"
};
const it = {
  "language": "Lingua",
  "eyebrow": "Un design per ogni umore.",
  "title": "Quale viso ti somiglia?",
  "intro": "Scegli un colore, prova un altro viso. Scopri il nuovo design di Head-Light.",
  "preview": "Anteprima della schermata Home",
  "choose": "Abbinalo come vuoi.",
  "reset": "Ripristina",
  "style": "Stile",
  "simple": "Semplice",
  "illustration": "Illustrazione",
  "background": "Sfondo",
  "accent": "Accento",
  "face": "Visi",
  "size": "Dimensione",
  "spacing": "Distanza",
  "height": "Altezza",
  "motion": "Battito di ciglia",
  "retro": "Modalità rétro",
  "note": "Prova alcune opzioni di design. In questa anteprima non puoi scrivere o registrare.",
  "release": "Il nuovo design arriverà con il prossimo aggiornamento dell’app.",
  "back": "← Informazioni su Head-Light",
  "white": "Bianco",
  "black": "Nero",
  "charcoal": "Antracite",
  "navy": "Mezzanotte",
  "cream": "Crema",
  "paper": "Carta",
  "mono": "Monocromatico",
  "sumi": "Inchiostro",
  "blue": "Blu",
  "lime": "Lime",
  "orange": "Arancione",
  "pink": "Rosa acceso",
  "lilac": "Lilla",
  "mint": "Menta",
  "lcdGreen": "Verde LCD",
  "amber": "Ambra",
  "sky": "Cielo",
  "rose": "Rosa",
  "smoke": "Fumo",
  "lavender": "Lavanda",
  "smile": "Sorriso",
  "kira": "Scintilla",
  "tare": "Dolce",
  "sleepy": "Sonno",
  "round": "Rotondo",
  "tojime": "Strizzato",
  "ring": "Sorpresa",
  "home": "Home",
  "words": "Parole",
  "collection": "Raccolta",
  "journal": "Diario",
  "ai": "Per IA"
};

export const copies = {ja,en,ko,de,"zh-Hant":zhHant,fr,es,it};
const extra = {
  "ja": {
    "classic": "デフォルト",
    "midnightCassette": "カセット",
    "warmAnalog": "アナログ",
    "cyberSignal": "シグナル",
    "dreamySticker": "ドリーム",
    "vividRed": "ビビッドレッド",
    "vividBlue": "ビビッドブルー",
    "vividGreen": "ビビッドグリーン",
    "vividYellow": "ビビッドイエロー",
    "cuteGlossy": "うるうる",
    "glossy": "つやつや",
    "retroEye": "レトロ",
    "mellow": "ギラリ",
    "curious": "ちぐはぐ",
    "starry": "ほしあかり",
    "body": "ボディー",
    "shuffle": "おまかせで着せ替え",
    "adjust": "顔を少し調整",
    "asleep": "おやすみ",
    "intro": "ボディーと顔を選ぶだけ。気分にぴったりのHead-Lightに。"
  },
  "en": {
    "classic": "Default",
    "midnightCassette": "Cassette",
    "warmAnalog": "Analog",
    "cyberSignal": "Signal",
    "dreamySticker": "Dream",
    "vividRed": "Vivid red",
    "vividBlue": "Vivid blue",
    "vividGreen": "Vivid green",
    "vividYellow": "Vivid yellow",
    "cuteGlossy": "Bright-eyed",
    "glossy": "Gleaming",
    "retroEye": "Retro",
    "mellow": "Fierce",
    "curious": "Quirky",
    "starry": "Starlight",
    "body": "Body",
    "shuffle": "Surprise me",
    "adjust": "Fine-tune the face",
    "asleep": "Asleep",
    "intro": "Pick a body and a face. Find a Head-Light that feels like you."
  },
  "ko": {
    "classic": "기본",
    "midnightCassette": "카세트",
    "warmAnalog": "아날로그",
    "cyberSignal": "시그널",
    "dreamySticker": "드림",
    "vividRed": "비비드 레드",
    "vividBlue": "비비드 블루",
    "vividGreen": "비비드 그린",
    "vividYellow": "비비드 옐로",
    "cuteGlossy": "초롱초롱",
    "glossy": "반짝반짝",
    "retroEye": "레트로",
    "mellow": "강렬한 눈",
    "curious": "짝짝이",
    "starry": "별빛",
    "body": "바디",
    "shuffle": "랜덤으로 꾸미기",
    "adjust": "얼굴 세부 조정",
    "asleep": "잘 자요",
    "intro": "바디와 얼굴을 고르면, 내 기분에 딱 맞는 Head-Light."
  },
  "de": {
    "classic": "Standard",
    "midnightCassette": "Kassette",
    "warmAnalog": "Analog",
    "cyberSignal": "Signal",
    "dreamySticker": "Traum",
    "vividRed": "Leuchtendes Rot",
    "vividBlue": "Leuchtendes Blau",
    "vividGreen": "Leuchtendes Grün",
    "vividYellow": "Leuchtendes Gelb",
    "cuteGlossy": "Kulleraugen",
    "glossy": "Glänzend",
    "retroEye": "Retro",
    "mellow": "Scharf",
    "curious": "Schräg",
    "starry": "Sternenlicht",
    "body": "Gehäuse",
    "shuffle": "Zufällig kombinieren",
    "adjust": "Gesicht anpassen",
    "asleep": "Schlafend",
    "intro": "Wähle Gehäuse und Gesicht. So fühlt sich Head-Light nach dir an."
  },
  "zh-Hant": {
    "classic": "預設",
    "midnightCassette": "卡帶",
    "warmAnalog": "類比",
    "cyberSignal": "訊號",
    "dreamySticker": "夢境",
    "vividRed": "鮮明紅",
    "vividBlue": "鮮明藍",
    "vividGreen": "鮮明綠",
    "vividYellow": "鮮明黃",
    "cuteGlossy": "水汪汪",
    "glossy": "亮晶晶",
    "retroEye": "復古",
    "mellow": "銳眼",
    "curious": "一大一小",
    "starry": "星光",
    "body": "機身",
    "shuffle": "隨機搭配",
    "adjust": "微調臉部",
    "asleep": "晚安",
    "intro": "選個機身，換張臉。搭配屬於你的 Head-Light。"
  },
  "fr": {
    "classic": "Par défaut",
    "midnightCassette": "Cassette",
    "warmAnalog": "Analogique",
    "cyberSignal": "Signal",
    "dreamySticker": "Rêve",
    "vividRed": "Rouge vif",
    "vividBlue": "Bleu vif",
    "vividGreen": "Vert vif",
    "vividYellow": "Jaune vif",
    "cuteGlossy": "Yeux brillants",
    "glossy": "Brillants",
    "retroEye": "Rétro",
    "mellow": "Intenses",
    "curious": "Décalés",
    "starry": "Étoilés",
    "body": "Boîtier",
    "shuffle": "Surprenez-moi",
    "adjust": "Ajuster le visage",
    "asleep": "Endormis",
    "intro": "Un boîtier, un visage. Trouvez le Head-Light qui vous ressemble."
  },
  "es": {
    "classic": "Predeterminado",
    "midnightCassette": "Casete",
    "warmAnalog": "Analógico",
    "cyberSignal": "Señal",
    "dreamySticker": "Sueño",
    "vividRed": "Rojo vivo",
    "vividBlue": "Azul vivo",
    "vividGreen": "Verde vivo",
    "vividYellow": "Amarillo vivo",
    "cuteGlossy": "Ojos tiernos",
    "glossy": "Brillantes",
    "retroEye": "Retro",
    "mellow": "Fieros",
    "curious": "Disparejos",
    "starry": "Luz estelar",
    "body": "Cuerpo",
    "shuffle": "Sorpréndeme",
    "adjust": "Ajustar la cara",
    "asleep": "Dormida",
    "intro": "Elige un cuerpo y una cara. Encuentra tu propio Head-Light."
  },
  "it": {
    "classic": "Predefinito",
    "midnightCassette": "Cassetta",
    "warmAnalog": "Analogico",
    "cyberSignal": "Segnale",
    "dreamySticker": "Sogno",
    "vividRed": "Rosso vivido",
    "vividBlue": "Blu vivido",
    "vividGreen": "Verde vivido",
    "vividYellow": "Giallo vivido",
    "cuteGlossy": "Occhi dolci",
    "glossy": "Lucenti",
    "retroEye": "Retrò",
    "mellow": "Feroce",
    "curious": "Spaiati",
    "starry": "Stellati",
    "body": "Corpo",
    "shuffle": "Sorprendimi",
    "adjust": "Regola il viso",
    "asleep": "Addormentato",
    "intro": "Scegli un corpo e un viso. Trova il tuo Head-Light."
  }
};
Object.entries(extra).forEach(([lang,values])=>Object.assign(copies[lang],values));
